### ISSUE TITLE
Obtain non-profit account on GitHub

### ISSUE THREAD

**Issue by thejameslang** [rare-genomics/rg-mobile#14]

**Comment by thejameslang** [comment]
@dianeoliveira do we meet the requirements listed here?

https://github.com/nonprofit

**Comment by dianeoliveira** [comment]
@thejameslang I'm waiting Ruma/Beatriz reply with our status (501).  My idea is exchange this repo in a nonprofit account. OK? 
Don't need create a new repo. We can still using this one. 

------------------ This is the information will send to Github----------------
- Nonprofit’s GitHub organization account name: rare-genomics

- Nonprofit's GitHub organization URL: https://github.com/orgs/rare-genomics/

- Local government (501(c)(3):  <???>

- Name of your nonprofit: Rare Genomics Institute

- Summary of what your nonprofit organization does: We are Rare Genomics Institute. A non-profit organization dedicated to helping rare disease patients find hope for a cure. We work alongside patients and their families, providing them with the necessary tools, knowledge, and connections so that they can better understand the cause of their disease.  We are building a mobile app for ours stakeholders as patients, donor, etc. And we are using GITHUB as our repository and management solution.

**Comment by dianeoliveira** [comment]
Requested sent to Github at 03/08/17 at 3:45

Hi Github! 

We are Rare Genomics Institute. A non-profit organization dedicated to helping rare disease patients find hope for a cure. We work alongside patients and their families, providing them with the necessary tools, knowledge, and connections so that they can better understand the cause of their disease. We are building a mobile app for ours stakeholders as patients, donor, etc. And we are using GITHUB as our repository and management solution.
Our website: www.raregenomics.org 

Below, please see more information about us: 

.Nonprofit’s GitHub organization account name: rare-genomics

.Nonprofit's GitHub organization URL: https://github.com/orgs/rare-genomics/

.Local government (501(c)(3): https://www.guidestar.org/profile/45-3624709

.Name of your nonprofit: Rare Genomics Institute

Thank you in advance. 

Diane Oliveira, PMP
Agile Project Manager - MApp Project 
Rare Genomics Institute
diane.oliveira@raregenomics.org
+1 202.340.2008

www.raregenomics.org
www.rareshare.org
RG Twitter
RG Facebook
RG LinkedIn

**Comment by dianeoliveira** [comment]
On Thu, Mar 9, 2017 at 9:45 AM, Lieke (GitHub Staff) <non-profit@github.com> wrote:
Hello Diane!

Thanks so much for getting in touch and for providing all the information we need to get you set up. Good news! We've upgraded your organization to our free non-profit plan (essentially applying a 100% discount to your account), giving you unlimited repos for your projects and unlimited users. We hope it's useful.

Sounds like a great project to be a part of - keep up the amazing work!

Thanks and GitHugs,

Lieke
